# Generated by Django 4.1.1 on 2022-09-07 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foot',
            new_name='Food',
        ),
        migrations.RenameModel(
            old_name='Housing',
            new_name='Hotel',
        ),
        migrations.RenameModel(
            old_name='Kind_transport',
            new_name='Transport',
        ),
    ]
